#ifndef CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H

// Generated by tools/release.py — edit that script, not these numbers.
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION "0.1.0"
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MAJOR 0
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MINOR 1
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_REVISION 0

namespace ConstexprCore {
// Version of the library, as "major.minor.revision".
inline constexpr const char* useful_abstractions_version = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION;
inline constexpr int useful_abstractions_version_major = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MAJOR;
inline constexpr int useful_abstractions_version_minor = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MINOR;
inline constexpr int useful_abstractions_version_revision = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_REVISION;
} // namespace ConstexprCore

#endif // CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H
