/* auto-generated on 2026-09-13 22:30:01 +0000. Do not edit! */
/*
 * ConstexprCore useful_abstractions 0.1.0 — single-header amalgamation.
 *
 * Compile-time perfect hashing for C++. Drop this file into your project and
 * #include it; it is self-contained and needs no other ConstexprCore headers.
 *
 * Requires C++23. Regenerate with singleheader/amalgamate.py.
 *
 * Bundled files, in order:
 *   ConstexprCore/useful_abstractions.h
 *   ConstexprCore/useful_abstractions_version.h
 *   ConstexprCore/constexpr_check.h
 *   ConstexprCore/constexpr_hash.h
 *   ConstexprCore/fixed_string.h
 *   ConstexprCore/constexpr_ptr.h
 *   ConstexprCore/escape_string.h
 *   ConstexprCore/type_name.h
 *   ConstexprCore/utf_convert.h
 */

/* begin file ConstexprCore/useful_abstractions.h */
#ifndef CONSTEXPRCORE_USEFUL_ABSTRACTIONS_H
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_H

// Umbrella header: everything the library offers, in one include.
//
// Each component is also usable on its own — include just
// <ConstexprCore/fixed_string.h> if that is all you need. This header exists
// so that "give me the whole library" is one line, and so that the
// single-header amalgamation (singleheader/useful_abstractions.h) has a root
// to walk from.

/* begin file ConstexprCore/useful_abstractions_version.h */
#ifndef CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H

// Generated by tools/release.py — edit that script, not these numbers.
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION "0.1.0"
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MAJOR 0
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MINOR 1
#define CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_REVISION 0

namespace ConstexprCore {
// Version of the library, as "major.minor.revision".
inline constexpr const char* useful_abstractions_version = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION;
inline constexpr int useful_abstractions_version_major = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MAJOR;
inline constexpr int useful_abstractions_version_minor = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_MINOR;
inline constexpr int useful_abstractions_version_revision = CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_REVISION;
} // namespace ConstexprCore

#endif // CONSTEXPRCORE_USEFUL_ABSTRACTIONS_VERSION_H
/* end file ConstexprCore/useful_abstractions_version.h */

/* begin file ConstexprCore/constexpr_check.h */
#ifndef CONSTEXPRCORE_CONSTEXPR_CHECK_H
#define CONSTEXPRCORE_CONSTEXPR_CHECK_H

#include <cstddef>

namespace ConstexprCore {

// ============================================================================
// Compile-time error utilities
// ============================================================================

/**
 * Triggers a compile-time error with a descriptive message.
 *
 * In a consteval context, throwing causes a compile-time error. The message
 * becomes part of the compiler's error output (compiler-dependent formatting).
 *
 * Example:
 *   consteval int must_be_positive(int x) {
 *     if (x <= 0) static_error("Value must be positive");
 *     return x;
 *   }
 *
 *   constexpr int a = must_be_positive(5);   // OK
 *   constexpr int b = must_be_positive(-1);  // Compile error!
 */
[[noreturn]] consteval void static_error(const char* message) {
  throw message;
}

/**
 * Compile-time assertion that can use runtime-computed conditions.
 *
 * Unlike static_assert, this works inside consteval functions with
 * conditions that depend on template parameters or consteval computation.
 *
 * Example:
 *   template <int N>
 *   consteval int factorial() {
 *     static_require(N >= 0, "factorial requires non-negative input");
 *     if constexpr (N <= 1) return 1;
 *     else return N * factorial<N - 1>();
 *   }
 */
consteval void static_require(bool condition, const char* message) {
  if (!condition) {
    throw message;
  }
}

// ============================================================================
// Error result types for detailed error reporting
// ============================================================================

/**
 * A compile-time error result that carries position information.
 *
 * Use this when you need to report where an error occurred in input data.
 */
template <typename ErrorEnum>
struct error_result {
  ErrorEnum error;
  std::size_t position;

  [[nodiscard]] constexpr bool ok() const noexcept {
    return error == ErrorEnum{};  // Assumes default value means "no error"
  }

  [[nodiscard]] constexpr explicit operator bool() const noexcept {
    return ok();
  }
};

// ============================================================================
// Require helper for error_result
// ============================================================================

/**
 * Throws a compile-time error if the result indicates failure.
 *
 * The message parameter should describe what was being validated.
 * For more specific error messages, handle error codes individually.
 */
template <typename ErrorEnum>
consteval void require_ok(const error_result<ErrorEnum>& result,
                          const char* message) {
  if (!result.ok()) {
    throw message;
  }
}

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_CONSTEXPR_CHECK_H
/* end file ConstexprCore/constexpr_check.h */
/* begin file ConstexprCore/constexpr_hash.h */
#ifndef CONSTEXPRCORE_CONSTEXPR_HASH_H
#define CONSTEXPRCORE_CONSTEXPR_HASH_H

/* begin file ConstexprCore/fixed_string.h */
#ifndef CONSTEXPRCORE_FIXED_STRING_H
#define CONSTEXPRCORE_FIXED_STRING_H

#include <algorithm>
#include <array>
#include <bit>
#include <compare>
#include <concepts>
#include <cstddef>
#include <span>
#include <string_view>
#include <type_traits>

namespace ConstexprCore {

// ============================================================================
// Concepts for character types
// ============================================================================

namespace detail {

template <typename T>
concept char_type = std::same_as<T, char> || std::same_as<T, wchar_t> ||
                    std::same_as<T, char8_t> || std::same_as<T, char16_t> ||
                    std::same_as<T, char32_t>;

}  // namespace detail

// ============================================================================
// fixed_string - Unified compile-time string type
// ============================================================================

/**
 * A fixed-size string that can be used as a non-type template parameter (C++20).
 *
 * This enables passing string literals directly to templates:
 *   template <fixed_string Name>
 *   struct named_type { ... };
 *
 *   using my_type = named_type<"hello">;
 *
 * @tparam CharT  Character type (char, char8_t, char16_t, char32_t, wchar_t)
 * @tparam N      Number of characters (excluding null terminator)
 * @tparam Endian Byte order for multi-byte characters (default: native)
 */
template <detail::char_type CharT, std::size_t N,
          std::endian Endian = std::endian::native>
struct fixed_string {
  using value_type = CharT;
  using size_type = std::size_t;
  using difference_type = std::ptrdiff_t;
  using pointer = CharT*;
  using const_pointer = const CharT*;
  using reference = CharT&;
  using const_reference = const CharT&;
  using iterator = CharT*;
  using const_iterator = const CharT*;

  static constexpr std::endian endianness = Endian;

  std::array<CharT, N> data{};

  constexpr fixed_string() = default;

  // Construct from string literal (array includes null terminator)
  constexpr fixed_string(const CharT (&str)[N + 1]) {
    std::copy_n(str, N, data.data());
  }

  // Construct from another array (for internal use, e.g., from literals)
  constexpr explicit fixed_string(const std::array<CharT, N>& arr) : data(arr) {}

  // Construct from range
  template <typename Range>
    requires std::ranges::input_range<Range> &&
             std::convertible_to<std::ranges::range_value_t<Range>, CharT>
  constexpr explicit fixed_string(Range&& range) {
    auto it = std::ranges::begin(range);
    for (std::size_t i = 0; i < N && it != std::ranges::end(range); ++i, ++it) {
      data[i] = static_cast<CharT>(*it);
    }
  }

  [[nodiscard]] static constexpr std::size_t size() noexcept { return N; }
  [[nodiscard]] static constexpr std::size_t length() noexcept { return N; }
  [[nodiscard]] static constexpr bool empty() noexcept { return N == 0; }

  // String view conversion (only for char types that support string_view)
  [[nodiscard]] constexpr std::basic_string_view<CharT> view() const noexcept
    requires std::same_as<CharT, char> || std::same_as<CharT, wchar_t> ||
             std::same_as<CharT, char8_t> || std::same_as<CharT, char16_t> ||
             std::same_as<CharT, char32_t>
  {
    return {data.data(), N};
  }

  [[nodiscard]] constexpr operator std::basic_string_view<CharT>() const noexcept
    requires std::same_as<CharT, char> || std::same_as<CharT, wchar_t> ||
             std::same_as<CharT, char8_t> || std::same_as<CharT, char16_t> ||
             std::same_as<CharT, char32_t>
  {
    return view();
  }

  [[nodiscard]] constexpr CharT* begin() noexcept { return data.data(); }
  [[nodiscard]] constexpr const CharT* begin() const noexcept { return data.data(); }
  [[nodiscard]] constexpr const CharT* cbegin() const noexcept { return data.data(); }

  [[nodiscard]] constexpr CharT* end() noexcept { return data.data() + N; }
  [[nodiscard]] constexpr const CharT* end() const noexcept { return data.data() + N; }
  [[nodiscard]] constexpr const CharT* cend() const noexcept { return data.data() + N; }

  [[nodiscard]] constexpr CharT& operator[](std::size_t i) noexcept {
    return data[i];
  }
  [[nodiscard]] constexpr const CharT& operator[](std::size_t i) const noexcept {
    return data[i];
  }

  [[nodiscard]] constexpr CharT& front() noexcept { return data[0]; }
  [[nodiscard]] constexpr const CharT& front() const noexcept { return data[0]; }

  [[nodiscard]] constexpr CharT& back() noexcept { return data[N - 1]; }
  [[nodiscard]] constexpr const CharT& back() const noexcept { return data[N - 1]; }

  [[nodiscard]] constexpr std::span<CharT, N> span() noexcept {
    return std::span<CharT, N>(data.data(), N);
  }
  [[nodiscard]] constexpr std::span<const CharT, N> span() const noexcept {
    return std::span<const CharT, N>(data.data(), N);
  }

  // Shrink to a smaller size (compile-time only)
  template <std::size_t NewSize>
    requires(NewSize <= N)
  [[nodiscard]] constexpr auto shrink() const noexcept {
    fixed_string<CharT, NewSize, Endian> result{};
    std::copy_n(data.data(), NewSize, result.data.data());
    return result;
  }

  // Convert to array of different type (same size)
  template <typename TargetT>
    requires(sizeof(TargetT) == sizeof(CharT))
  [[nodiscard]] constexpr std::array<TargetT, N> as_array() const noexcept {
    std::array<TargetT, N> result{};
    for (std::size_t i = 0; i < N; ++i) {
      result[i] = static_cast<TargetT>(data[i]);
    }
    return result;
  }

  // Concatenation (for same CharT and Endian)
  template <std::size_t M>
  [[nodiscard]] constexpr auto operator+(const fixed_string<CharT, M, Endian>& other) const {
    fixed_string<CharT, N + M, Endian> result{};
    std::copy_n(data.data(), N, result.data.data());
    std::copy_n(other.data.data(), M, result.data.data() + N);
    return result;
  }

  template <std::size_t M>
  [[nodiscard]] constexpr bool
  operator==(const fixed_string<CharT, M, Endian>& other) const {
    if constexpr (N != M) {
      return false;
    } else {
      return std::equal(data.begin(), data.end(), other.data.begin());
    }
  }

  template <std::size_t M>
  [[nodiscard]] constexpr auto
  operator<=>(const fixed_string<CharT, M, Endian>& other) const {
    return std::lexicographical_compare_three_way(
        data.begin(), data.end(),
        other.data.begin(), other.data.end());
  }
};

// Deduction guides
template <detail::char_type CharT, std::size_t N>
fixed_string(const CharT (&)[N]) -> fixed_string<CharT, N - 1>;

// ============================================================================
// Type traits and concepts for fixed_string
// ============================================================================

template <typename T>
struct is_fixed_string : std::false_type {};

template <detail::char_type CharT, std::size_t N, std::endian E>
struct is_fixed_string<fixed_string<CharT, N, E>> : std::true_type {};

template <typename T>
inline constexpr bool is_fixed_string_v = is_fixed_string<T>::value;

template <typename T>
concept any_fixed_string = is_fixed_string_v<std::remove_cvref_t<T>>;

template <typename T>
concept utf8_fixed_string = any_fixed_string<T> &&
    (std::same_as<typename std::remove_cvref_t<T>::value_type, char8_t> ||
     std::same_as<typename std::remove_cvref_t<T>::value_type, char>);

template <typename T>
concept utf16_fixed_string = any_fixed_string<T> &&
    std::same_as<typename std::remove_cvref_t<T>::value_type, char16_t>;

template <typename T>
concept utf32_fixed_string = any_fixed_string<T> &&
    std::same_as<typename std::remove_cvref_t<T>::value_type, char32_t>;

// ============================================================================
// string_literal - Helper for user-defined literal operators
// ============================================================================

namespace detail {

/**
 * Helper to capture string literals with their size for UDL operators.
 * Strips the null terminator from size calculation.
 */
template <char_type CharT, std::size_t N>
struct string_literal {
  std::array<CharT, N - 1> storage{};
  using type = CharT;

  static constexpr std::size_t size() noexcept { return N - 1; }

  constexpr string_literal(const CharT (&str)[N]) {
    static_assert(N >= 1, "String literal must have at least null terminator");
    std::copy_n(str, N - 1, storage.data());
  }
};

}  // namespace detail

// ============================================================================
// User-defined literals
// ============================================================================

inline namespace literals {
inline namespace string_literals {

/**
 * Create a fixed_string<char, N> from a string literal.
 * Usage: "hello"_fs
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_fs() noexcept {
  return fixed_string<char, Lit.size()>(Lit.storage);
}

/**
 * Create a fixed_string<char8_t, N> for UTF-8.
 * Usage: u8"hello"_u8
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_u8() noexcept {
  return fixed_string<char8_t, Lit.size()>(Lit.storage);
}

/**
 * Create a fixed_string<char16_t, N> for UTF-16 (native endian).
 * Usage: u"hello"_u16
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_u16() noexcept {
  return fixed_string<char16_t, Lit.size()>(Lit.storage);
}

/**
 * Create a fixed_string<char16_t, N> for UTF-16 little-endian.
 * Usage: u"hello"_u16le
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_u16le() noexcept {
  return fixed_string<char16_t, Lit.size(), std::endian::little>(Lit.storage);
}

/**
 * Create a fixed_string<char16_t, N> for UTF-16 big-endian.
 * Usage: u"hello"_u16be
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_u16be() noexcept {
  return fixed_string<char16_t, Lit.size(), std::endian::big>(Lit.storage);
}

/**
 * Create a fixed_string<char32_t, N> for UTF-32.
 * Usage: U"hello"_u32
 */
template <detail::string_literal Lit>
[[nodiscard]] consteval auto operator""_u32() noexcept {
  return fixed_string<char32_t, Lit.size()>(Lit.storage);
}

}  // namespace string_literals
}  // namespace literals

// ============================================================================
// string_constant - Type-level string wrapper
// ============================================================================

/**
 * Wraps a fixed_string as a type, exposing it as a static constexpr value.
 *
 * Useful when you need to pass strings as type parameters:
 *   using name = string_constant<"hello">;
 *   constexpr auto s = name::value;  // "hello"
 */
template <fixed_string Str>
struct string_constant {
  static constexpr std::string_view value = Str.view();
  static constexpr auto string = Str;

  [[nodiscard]] constexpr operator std::string_view() const noexcept {
    return value;
  }
};

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_FIXED_STRING_H
/* end file ConstexprCore/fixed_string.h */

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace ConstexprCore {

// ============================================================================
// FNV-1a Hash Algorithm - Compile-time string hashing
// ============================================================================

namespace detail {

// FNV-1a constants based on hash size
template <std::size_t BitWidth>
struct fnv1a_params;

template <>
struct fnv1a_params<32> {
  static constexpr std::uint32_t offset_basis = 2166136261u;
  static constexpr std::uint32_t prime = 16777619u;
};

template <>
struct fnv1a_params<64> {
  static constexpr std::uint64_t offset_basis = 14695981039346656037ull;
  static constexpr std::uint64_t prime = 1099511628211ull;
};

// Type-based wrapper that selects params based on sizeof(T)
template <typename SizeT>
struct fnv1a_constants : fnv1a_params<sizeof(SizeT) * 8> {};

}  // namespace detail

/**
 * Compute FNV-1a hash at compile-time.
 *
 * FNV-1a is a non-cryptographic hash function known for:
 * - Simple implementation
 * - Good distribution
 * - Fast computation
 * - Works well for hash tables
 *
 * @param str The string view to hash
 * @return The hash value
 *
 * Example:
 *   constexpr auto h = fnv1a("hello");
 *   static_assert(h == fnv1a("hello"));  // Same input -> same hash
 */
template <typename CharT = char, typename SizeT = std::size_t>
[[nodiscard]] constexpr SizeT
fnv1a(std::basic_string_view<CharT> str) noexcept {
  using constants = detail::fnv1a_constants<SizeT>;

  SizeT hash = constants::offset_basis;
  for (CharT c : str) {
    // Cast to unsigned byte for consistent hashing
    auto byte = static_cast<unsigned char>(c);
    hash ^= static_cast<SizeT>(byte);
    hash *= constants::prime;
  }
  return hash;
}

/**
 * Overload for C-style string with known length.
 */
template <typename CharT = char, typename SizeT = std::size_t>
[[nodiscard]] constexpr SizeT fnv1a(const CharT* str,
                                    std::size_t len) noexcept {
  return fnv1a<CharT, SizeT>(std::basic_string_view<CharT>{str, len});
}

/**
 * Overload for null-terminated C-style strings.
 * Note: Requires iterating to find length, prefer string_view overload.
 */
template <typename CharT = char, typename SizeT = std::size_t>
[[nodiscard]] constexpr SizeT fnv1a(const CharT* str) noexcept {
  using constants = detail::fnv1a_constants<SizeT>;

  SizeT hash = constants::offset_basis;
  while (*str) {
    auto byte = static_cast<unsigned char>(*str);
    hash ^= static_cast<SizeT>(byte);
    hash *= constants::prime;
    ++str;
  }
  return hash;
}

/**
 * Overload for fixed_string.
 */
template <detail::char_type CharT, std::size_t N, std::endian E,
          typename SizeT = std::size_t>
[[nodiscard]] constexpr SizeT
fnv1a(const fixed_string<CharT, N, E>& str) noexcept {
  return fnv1a<CharT, SizeT>(std::basic_string_view<CharT>{str.data.data(), N});
}

// ============================================================================
// Hash template variable - hash_v<"string">
// ============================================================================

/**
 * Compile-time hash value for a fixed_string.
 *
 * Example:
 *   constexpr auto h = hash_v<"hello">;
 *   static_assert(h != hash_v<"world">);
 */
template <fixed_string S>
inline constexpr std::size_t hash_v = fnv1a(S.view());

// ============================================================================
// User-defined literals
// ============================================================================

inline namespace literals {
inline namespace hash_literals {

/**
 * User-defined literal for compile-time string hashing.
 *
 * Example:
 *   using namespace comptime::literals;
 *
 *   constexpr auto h = "hello"_hash;
 *
 *   // Use in switch statements:
 *   switch (fnv1a(runtime_string)) {
 *     case "GET"_hash:  handle_get();  break;
 *     case "POST"_hash: handle_post(); break;
 *     case "PUT"_hash:  handle_put();  break;
 *   }
 */
[[nodiscard]] consteval std::size_t operator""_hash(const char* str,
                                                    std::size_t len) noexcept {
  return fnv1a(std::string_view{str, len});
}

/**
 * Wide string literal variant.
 */
[[nodiscard]] consteval std::size_t operator""_hash(const wchar_t* str,
                                                    std::size_t len) noexcept {
  return fnv1a(std::wstring_view{str, len});
}

/**
 * char8_t string literal variant (UTF-8).
 */
[[nodiscard]] consteval std::size_t operator""_hash(const char8_t* str,
                                                    std::size_t len) noexcept {
  return fnv1a(std::u8string_view{str, len});
}

/**
 * char16_t string literal variant (UTF-16).
 */
[[nodiscard]] consteval std::size_t operator""_hash(const char16_t* str,
                                                    std::size_t len) noexcept {
  return fnv1a(std::u16string_view{str, len});
}

/**
 * char32_t string literal variant (UTF-32).
 */
[[nodiscard]] consteval std::size_t operator""_hash(const char32_t* str,
                                                    std::size_t len) noexcept {
  return fnv1a(std::u32string_view{str, len});
}

/**
 * 32-bit hash variant for when you need smaller hash values.
 */
[[nodiscard]] consteval std::uint32_t operator""_hash32(const char* str,
                                                        std::size_t len) noexcept {
  return fnv1a<char, std::uint32_t>(std::string_view{str, len});
}

/**
 * 64-bit hash variant for explicit 64-bit hashing.
 */
[[nodiscard]] consteval std::uint64_t operator""_hash64(const char* str,
                                                        std::size_t len) noexcept {
  return fnv1a<char, std::uint64_t>(std::string_view{str, len});
}

}  // namespace hash_literals
}  // namespace literals

// ============================================================================
// Constexpr hash functor - for use in compile-time containers
// ============================================================================

/**
 * A constexpr hash functor compatible with std::hash interface.
 *
 * Can be used as a drop-in replacement for std::hash in constexpr contexts.
 *
 * Example:
 *   constexpr constexpr_hash<std::string_view> hasher;
 *   constexpr auto h = hasher("hello");
 */
template <typename T>
struct constexpr_hash {
  using argument_type = T;
  using result_type = std::size_t;

  [[nodiscard]] constexpr std::size_t operator()(const T& str) const noexcept {
    return fnv1a(str);
  }
};

// ============================================================================
// Hash combine utility
// ============================================================================

/**
 * Combine two hash values into one.
 *
 * Useful for hashing composite types or multiple values.
 *
 * Example:
 *   constexpr auto h1 = fnv1a("key");
 *   constexpr auto h2 = fnv1a("value");
 *   constexpr auto combined = hash_combine(h1, h2);
 */
[[nodiscard]] constexpr std::size_t hash_combine(std::size_t h1,
                                                 std::size_t h2) noexcept {
  // Boost-style hash combine
  return h1 ^ (h2 + 0x9e3779b9 + (h1 << 6) + (h1 >> 2));
}

/**
 * Variadic hash combine.
 */
template <typename... Hashes>
[[nodiscard]] constexpr std::size_t hash_combine(std::size_t h1,
                                                 std::size_t h2,
                                                 Hashes... rest) noexcept {
  return hash_combine(hash_combine(h1, h2), rest...);
}

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_CONSTEXPR_HASH_H
/* end file ConstexprCore/constexpr_hash.h */
/* begin file ConstexprCore/constexpr_ptr.h */
#ifndef CONSTEXPRCORE_CONSTEXPR_PTR_H
#define CONSTEXPRCORE_CONSTEXPR_PTR_H

#include <bit>
#include <concepts>
#include <cstddef>
#include <iterator>
#include <type_traits>

namespace ConstexprCore {

// ============================================================================
// reinterpret_ptr - Constexpr-safe type-punning pointer wrapper (read-only)
// ============================================================================

/**
 * A pointer wrapper that enables type-punning in constexpr contexts.
 *
 * Standard C++ does not allow reinterpret_cast during constant evaluation.
 * This wrapper provides a constexpr-safe alternative by using static_cast
 * on the values (not pointers) when types have the same size.
 *
 * Use case: Reading char arrays as uint8_t, signed/unsigned conversions,
 * or any scenario where you need to view memory as a different type.
 *
 * @tparam ViewAs  The type to interpret values as when dereferencing
 * @tparam ActualT The actual pointed-to type
 *
 * Requires: sizeof(ViewAs) == sizeof(ActualT)
 *
 * Example:
 *   constexpr char data[] = {'A', 'B', 'C'};
 *   constexpr reinterpret_ptr<uint8_t, char> ptr{data};
 *   static_assert(*ptr == 65);  // 'A' viewed as uint8_t
 */
template <typename ViewAs, typename ActualT>
  requires(sizeof(ViewAs) == sizeof(ActualT))
struct reinterpret_ptr {
  using element_type = ViewAs;
  using pointer = const ActualT*;
  using difference_type = std::ptrdiff_t;
  using iterator_category = std::random_access_iterator_tag;

  const ActualT* ptr;

  constexpr explicit reinterpret_ptr(const ActualT* p) noexcept : ptr(p) {}

  // Dereferencing - returns value bit-cast to ViewAs
  [[nodiscard]] constexpr ViewAs operator*() const noexcept {
    return std::bit_cast<ViewAs>(*ptr);
  }

  [[nodiscard]] constexpr ViewAs operator[](difference_type n) const noexcept {
    return std::bit_cast<ViewAs>(ptr[n]);
  }

  // Increment/Decrement
  constexpr reinterpret_ptr& operator++() noexcept {
    ++ptr;
    return *this;
  }

  constexpr reinterpret_ptr operator++(int) noexcept {
    auto old = *this;
    ++ptr;
    return old;
  }

  constexpr reinterpret_ptr& operator--() noexcept {
    --ptr;
    return *this;
  }

  constexpr reinterpret_ptr operator--(int) noexcept {
    auto old = *this;
    --ptr;
    return old;
  }

  // Arithmetic
  constexpr reinterpret_ptr& operator+=(difference_type n) noexcept {
    ptr += n;
    return *this;
  }

  constexpr reinterpret_ptr& operator-=(difference_type n) noexcept {
    ptr -= n;
    return *this;
  }

  [[nodiscard]] constexpr reinterpret_ptr
  operator+(difference_type n) const noexcept {
    return reinterpret_ptr{ptr + n};
  }

  [[nodiscard]] constexpr reinterpret_ptr
  operator-(difference_type n) const noexcept {
    return reinterpret_ptr{ptr - n};
  }

  [[nodiscard]] constexpr difference_type
  operator-(const reinterpret_ptr& other) const noexcept {
    return ptr - other.ptr;
  }

  // Comparison
  [[nodiscard]] constexpr bool
  operator==(const reinterpret_ptr& other) const noexcept {
    return ptr == other.ptr;
  }

  [[nodiscard]] constexpr auto
  operator<=>(const reinterpret_ptr& other) const noexcept {
    return ptr <=> other.ptr;
  }

  // Access to underlying pointer (as const void* for type safety)
  [[nodiscard]] constexpr const void* get() const noexcept { return ptr; }

  // Get underlying raw pointer (use with caution)
  [[nodiscard]] constexpr const ActualT* raw() const noexcept { return ptr; }

  [[nodiscard]] constexpr explicit operator bool() const noexcept {
    return ptr != nullptr;
  }
};

// Non-member addition for symmetry: n + ptr
template <typename ViewAs, typename ActualT>
[[nodiscard]] constexpr reinterpret_ptr<ViewAs, ActualT>
operator+(std::ptrdiff_t n, reinterpret_ptr<ViewAs, ActualT> p) noexcept {
  return p + n;
}

// ============================================================================
// make_reinterpret_ptr - Factory function
// ============================================================================

/**
 * Create a reinterpret_ptr with deduced actual type.
 *
 * Example:
 *   constexpr char data[] = "hello";
 *   auto ptr = make_reinterpret_ptr<uint8_t>(data);
 */
template <typename ViewAs, typename ActualT>
[[nodiscard]] constexpr reinterpret_ptr<ViewAs, ActualT>
make_reinterpret_ptr(const ActualT* p) noexcept {
  return reinterpret_ptr<ViewAs, ActualT>{p};
}

// ============================================================================
// write_proxy - Helper for writable type-punning
// ============================================================================

/**
 * Proxy returned by writable_ptr's operator* to enable "*ptr = value" syntax.
 */
template <typename WriteAs, typename ActualT>
struct write_proxy {
  ActualT* ptr;

  constexpr explicit write_proxy(ActualT* p) noexcept : ptr(p) {}

  constexpr write_proxy& operator=(WriteAs value) noexcept {
    *ptr = std::bit_cast<ActualT>(value);
    return *this;
  }

  // Allow reading the value too
  [[nodiscard]] constexpr operator WriteAs() const noexcept {
    return std::bit_cast<WriteAs>(*ptr);
  }
};

// ============================================================================
// writable_ptr - Constexpr-safe type-punning pointer wrapper (read-write)
// ============================================================================

/**
 * A writable version of reinterpret_ptr for type-punning writes in constexpr.
 *
 * Enables writing values of type WriteAs into storage of type ActualT,
 * with proper static_cast conversion.
 *
 * @tparam WriteAs The type to write values as
 * @tparam ActualT The actual pointed-to storage type
 *
 * Requires: sizeof(WriteAs) == sizeof(ActualT)
 *
 * Example:
 *   char buffer[4] = {};
 *   writable_ptr<uint8_t, char> ptr{buffer};
 *   *ptr = 255;  // Writes to buffer[0] as char(255)
 */
template <typename WriteAs, typename ActualT>
  requires(sizeof(WriteAs) == sizeof(ActualT))
struct writable_ptr {
  using element_type = WriteAs;
  using pointer = ActualT*;
  using difference_type = std::ptrdiff_t;

  ActualT* ptr;

  constexpr explicit writable_ptr(ActualT* p) noexcept : ptr(p) {}

  // Dereferencing - returns proxy for assignment
  [[nodiscard]] constexpr write_proxy<WriteAs, ActualT>
  operator*() const noexcept {
    return write_proxy<WriteAs, ActualT>{ptr};
  }

  [[nodiscard]] constexpr write_proxy<WriteAs, ActualT>
  operator[](difference_type n) const noexcept {
    return write_proxy<WriteAs, ActualT>{ptr + n};
  }

  // Increment/Decrement
  constexpr writable_ptr& operator++() noexcept {
    ++ptr;
    return *this;
  }

  constexpr writable_ptr operator++(int) noexcept {
    auto old = *this;
    ++ptr;
    return old;
  }

  constexpr writable_ptr& operator--() noexcept {
    --ptr;
    return *this;
  }

  constexpr writable_ptr operator--(int) noexcept {
    auto old = *this;
    --ptr;
    return old;
  }

  // Arithmetic
  constexpr writable_ptr& operator+=(difference_type n) noexcept {
    ptr += n;
    return *this;
  }

  constexpr writable_ptr& operator-=(difference_type n) noexcept {
    ptr -= n;
    return *this;
  }

  [[nodiscard]] constexpr writable_ptr
  operator+(difference_type n) const noexcept {
    return writable_ptr{ptr + n};
  }

  [[nodiscard]] constexpr writable_ptr
  operator-(difference_type n) const noexcept {
    return writable_ptr{ptr - n};
  }

  [[nodiscard]] constexpr difference_type
  operator-(const writable_ptr& other) const noexcept {
    return ptr - other.ptr;
  }

  // Comparison
  [[nodiscard]] constexpr bool
  operator==(const writable_ptr& other) const noexcept {
    return ptr == other.ptr;
  }

  [[nodiscard]] constexpr auto
  operator<=>(const writable_ptr& other) const noexcept {
    return ptr <=> other.ptr;
  }

  // Access to underlying pointer
  [[nodiscard]] constexpr ActualT* get() const noexcept { return ptr; }

  [[nodiscard]] constexpr explicit operator bool() const noexcept {
    return ptr != nullptr;
  }
};

// ============================================================================
// make_writable_ptr - Factory function
// ============================================================================

/**
 * Create a writable_ptr with deduced actual type.
 *
 * Example:
 *   char buffer[4] = {};
 *   auto ptr = make_writable_ptr<uint8_t>(buffer);
 *   *ptr = 255;
 */
template <typename WriteAs, typename ActualT>
[[nodiscard]] constexpr writable_ptr<WriteAs, ActualT>
make_writable_ptr(ActualT* p) noexcept {
  return writable_ptr<WriteAs, ActualT>{p};
}

// ============================================================================
// Type traits
// ============================================================================

template <typename T>
struct is_reinterpret_ptr : std::false_type {};

template <typename V, typename A>
struct is_reinterpret_ptr<reinterpret_ptr<V, A>> : std::true_type {};

template <typename T>
inline constexpr bool is_reinterpret_ptr_v = is_reinterpret_ptr<T>::value;

template <typename T>
struct is_writable_ptr : std::false_type {};

template <typename W, typename A>
struct is_writable_ptr<writable_ptr<W, A>> : std::true_type {};

template <typename T>
inline constexpr bool is_writable_ptr_v = is_writable_ptr<T>::value;

// ============================================================================
// Concepts
// ============================================================================

template <typename T>
concept any_reinterpret_ptr = is_reinterpret_ptr_v<std::remove_cvref_t<T>>;

template <typename T>
concept any_writable_ptr = is_writable_ptr_v<std::remove_cvref_t<T>>;

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_CONSTEXPR_PTR_H
/* end file ConstexprCore/constexpr_ptr.h */
/* begin file ConstexprCore/escape_string.h */
#ifndef CONSTEXPRCORE_ESCAPE_STRING_H
#define CONSTEXPRCORE_ESCAPE_STRING_H

/* skipped duplicate ConstexprCore/fixed_string.h */

#include <cstddef>

namespace ConstexprCore {

// ============================================================================
// Compile-time string escaping utilities
// ============================================================================

namespace detail {

// Hex digit conversion
constexpr char to_hex_digit(unsigned char nibble) noexcept {
  return nibble < 10 ? ('0' + nibble) : ('a' + nibble - 10);
}

// JSON escape output size for a single character
constexpr std::size_t json_char_escape_size(char c) noexcept {
  switch (c) {
    case '"':
    case '\\':
    case '\b':
    case '\f':
    case '\n':
    case '\r':
    case '\t':
      return 2;
    default:
      if (static_cast<unsigned char>(c) < 0x20) {
        return 6;  // \uXXXX
      }
      return 1;
  }
}

// Write a JSON-escaped character, returns number of chars written
constexpr std::size_t write_json_escaped_char(char c, char* out) noexcept {
  switch (c) {
    case '"':
      out[0] = '\\';
      out[1] = '"';
      return 2;
    case '\\':
      out[0] = '\\';
      out[1] = '\\';
      return 2;
    case '\b':
      out[0] = '\\';
      out[1] = 'b';
      return 2;
    case '\f':
      out[0] = '\\';
      out[1] = 'f';
      return 2;
    case '\n':
      out[0] = '\\';
      out[1] = 'n';
      return 2;
    case '\r':
      out[0] = '\\';
      out[1] = 'r';
      return 2;
    case '\t':
      out[0] = '\\';
      out[1] = 't';
      return 2;
    default:
      if (static_cast<unsigned char>(c) < 0x20) {
        out[0] = '\\';
        out[1] = 'u';
        out[2] = '0';
        out[3] = '0';
        out[4] = to_hex_digit((c >> 4) & 0x0F);
        out[5] = to_hex_digit(c & 0x0F);
        return 6;
      }
      out[0] = c;
      return 1;
  }
}

// Calculate total JSON escaped size
template <fixed_string Str>
consteval std::size_t json_escape_output_size() noexcept {
  std::size_t result = 0;
  for (std::size_t i = 0; i < Str.size(); ++i) {
    result += json_char_escape_size(Str.data[i]);
  }
  return result;
}

// Calculate JSON quoted size (with surrounding quotes)
template <fixed_string Str>
consteval std::size_t json_quoted_output_size() noexcept {
  return 2 + json_escape_output_size<Str>();
}

// Percent encoding requirements (URL encoding)
constexpr bool needs_percent_encode(char c) noexcept {
  // Unreserved characters in RFC 3986
  if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
      (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~') {
    return false;
  }
  return true;
}

// Calculate percent-encoded size
template <fixed_string Str>
consteval std::size_t percent_encode_output_size() noexcept {
  std::size_t result = 0;
  for (std::size_t i = 0; i < Str.size(); ++i) {
    result += needs_percent_encode(Str.data[i]) ? 3 : 1;
  }
  return result;
}

}  // namespace detail

// ============================================================================
// JSON escaping
// ============================================================================

/**
 * Escape a string for use in JSON at compile time.
 *
 * Escapes the following characters:
 * - " -> \"
 * - \ -> \\
 * - Control characters (< 0x20) -> \uXXXX
 * - Special characters: \b, \f, \n, \r, \t
 *
 * Example:
 *   constexpr auto escaped = json_escape<"Hello \"World\"">();
 *   // Result: Hello \"World\"
 */
template <fixed_string Str>
consteval auto json_escape() {
  constexpr std::size_t output_len = detail::json_escape_output_size<Str>();

  fixed_string<char, output_len> result{};
  std::size_t out_idx = 0;

  for (std::size_t i = 0; i < Str.size(); ++i) {
    out_idx += detail::write_json_escaped_char(Str.data[i], &result.data[out_idx]);
  }

  return result;
}

/**
 * Quote and escape a string for JSON at compile time.
 *
 * Adds surrounding double quotes and escapes the content.
 *
 * Example:
 *   constexpr auto quoted = json_quoted<"Hello \"World\"">();
 *   // Result: "Hello \"World\""
 */
template <fixed_string Str>
consteval auto json_quoted() {
  constexpr std::size_t output_len = detail::json_quoted_output_size<Str>();

  fixed_string<char, output_len> result{};
  std::size_t out_idx = 0;

  result.data[out_idx++] = '"';
  for (std::size_t i = 0; i < Str.size(); ++i) {
    out_idx += detail::write_json_escaped_char(Str.data[i], &result.data[out_idx]);
  }
  result.data[out_idx++] = '"';

  return result;
}

// ============================================================================
// URL percent encoding
// ============================================================================

/**
 * Percent-encode a string for use in URLs at compile time.
 *
 * Encodes all characters except unreserved characters (A-Z, a-z, 0-9, -, _, ., ~)
 * per RFC 3986.
 *
 * Example:
 *   constexpr auto encoded = percent_encode<"Hello World!">();
 *   // Result: Hello%20World%21
 */
template <fixed_string Str>
consteval auto percent_encode() {
  constexpr std::size_t output_len = detail::percent_encode_output_size<Str>();

  fixed_string<char, output_len> result{};
  std::size_t out_idx = 0;

  for (std::size_t i = 0; i < Str.size(); ++i) {
    char c = Str.data[i];

    if (!detail::needs_percent_encode(c)) {
      result.data[out_idx++] = c;
    } else {
      result.data[out_idx++] = '%';
      result.data[out_idx++] =
          detail::to_hex_digit((static_cast<unsigned char>(c) >> 4) & 0x0F);
      result.data[out_idx++] =
          detail::to_hex_digit(static_cast<unsigned char>(c) & 0x0F);
    }
  }

  return result;
}

// ============================================================================
// HTML entity encoding
// ============================================================================

namespace detail {

// HTML escape requirements
constexpr bool needs_html_escape(char c) noexcept {
  return c == '&' || c == '<' || c == '>' || c == '"' || c == '\'';
}

// HTML escape output size
constexpr std::size_t html_escape_size(char c) noexcept {
  switch (c) {
    case '&':
      return 5;  // &amp;
    case '<':
      return 4;  // &lt;
    case '>':
      return 4;  // &gt;
    case '"':
      return 6;  // &quot;
    case '\'':
      return 6;  // &#x27;
    default:
      return 1;
  }
}

template <fixed_string Str>
consteval std::size_t html_escape_output_size() noexcept {
  std::size_t result = 0;
  for (std::size_t i = 0; i < Str.size(); ++i) {
    result += html_escape_size(Str.data[i]);
  }
  return result;
}

}  // namespace detail

/**
 * Escape a string for safe use in HTML at compile time.
 *
 * Escapes the following characters:
 * - & -> &amp;
 * - < -> &lt;
 * - > -> &gt;
 * - " -> &quot;
 * - ' -> &#x27;
 *
 * Example:
 *   constexpr auto escaped = html_escape<"<script>alert('XSS')</script>">();
 *   // Result: &lt;script&gt;alert(&#x27;XSS&#x27;)&lt;/script&gt;
 */
template <fixed_string Str>
consteval auto html_escape() {
  constexpr std::size_t output_len = detail::html_escape_output_size<Str>();

  fixed_string<char, output_len> result{};
  std::size_t out_idx = 0;

  for (std::size_t i = 0; i < Str.size(); ++i) {
    char c = Str.data[i];

    switch (c) {
      case '&':
        result.data[out_idx++] = '&';
        result.data[out_idx++] = 'a';
        result.data[out_idx++] = 'm';
        result.data[out_idx++] = 'p';
        result.data[out_idx++] = ';';
        break;
      case '<':
        result.data[out_idx++] = '&';
        result.data[out_idx++] = 'l';
        result.data[out_idx++] = 't';
        result.data[out_idx++] = ';';
        break;
      case '>':
        result.data[out_idx++] = '&';
        result.data[out_idx++] = 'g';
        result.data[out_idx++] = 't';
        result.data[out_idx++] = ';';
        break;
      case '"':
        result.data[out_idx++] = '&';
        result.data[out_idx++] = 'q';
        result.data[out_idx++] = 'u';
        result.data[out_idx++] = 'o';
        result.data[out_idx++] = 't';
        result.data[out_idx++] = ';';
        break;
      case '\'':
        result.data[out_idx++] = '&';
        result.data[out_idx++] = '#';
        result.data[out_idx++] = 'x';
        result.data[out_idx++] = '2';
        result.data[out_idx++] = '7';
        result.data[out_idx++] = ';';
        break;
      default:
        result.data[out_idx++] = c;
        break;
    }
  }

  return result;
}

// ============================================================================
// Size query functions
// ============================================================================

/**
 * Get the size of a JSON-escaped string without allocating.
 */
template <fixed_string Str>
consteval std::size_t json_escape_size() noexcept {
  return detail::json_escape_output_size<Str>();
}

/**
 * Get the size of a percent-encoded string without allocating.
 */
template <fixed_string Str>
consteval std::size_t percent_encode_size() noexcept {
  return detail::percent_encode_output_size<Str>();
}

/**
 * Get the size of an HTML-escaped string without allocating.
 */
template <fixed_string Str>
consteval std::size_t html_escape_size() noexcept {
  return detail::html_escape_output_size<Str>();
}

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_ESCAPE_STRING_H
/* end file ConstexprCore/escape_string.h */
/* skipped duplicate ConstexprCore/fixed_string.h */
/* begin file ConstexprCore/type_name.h */
#ifndef CONSTEXPRCORE_TYPE_NAME_H
#define CONSTEXPRCORE_TYPE_NAME_H

/* skipped duplicate ConstexprCore/constexpr_hash.h */

#include <array>
#include <cstddef>
#include <string_view>

namespace ConstexprCore {

// ============================================================================
// Compile-time type name extraction
// ============================================================================

namespace detail {

/**
 * Extract type name from compiler's function signature.
 *
 * Different compilers embed type information differently:
 * - GCC/Clang: Uses __PRETTY_FUNCTION__
 * - MSVC: Uses __FUNCSIG__
 *
 * This function parses the signature to extract just the type name.
 */
template <typename T>
consteval std::string_view type_name_impl() noexcept {
#if defined(__clang__)
  // Clang format: "std::string_view comptime::detail::type_name_impl() [T = int]"
  constexpr std::string_view function = __PRETTY_FUNCTION__;
  constexpr std::string_view prefix = "[T = ";
  constexpr std::string_view suffix = "]";
#elif defined(__GNUC__)
  // GCC format: "consteval std::string_view comptime::detail::type_name_impl() [with T = int; ...]"
  constexpr std::string_view function = __PRETTY_FUNCTION__;
  constexpr std::string_view prefix = "[with T = ";
  constexpr std::string_view suffix = ";";  // GCC may have "; ..." after
#elif defined(_MSC_VER)
  // MSVC format: "class std::basic_string_view<char,...> __cdecl comptime::detail::type_name_impl<int>(void)"
  constexpr std::string_view function = __FUNCSIG__;
  constexpr std::string_view prefix = "type_name_impl<";
  constexpr std::string_view suffix = ">(void)";
#else
#error "Unsupported compiler for type_name"
#endif

  // Find the start of the type name
  constexpr std::size_t start = function.find(prefix);
  static_assert(start != std::string_view::npos, "Could not find type prefix");

  constexpr std::size_t type_start = start + prefix.size();

  // Find the end of the type name
  // For GCC, we need to handle both ';' and ']' since the format can vary
#if defined(__GNUC__) && !defined(__clang__)
  // GCC might use ';' or just ']' depending on context
  constexpr std::size_t semi_pos = function.find(';', type_start);
  constexpr std::size_t bracket_pos = function.find(']', type_start);
  constexpr std::size_t type_end =
      (semi_pos != std::string_view::npos && semi_pos < bracket_pos)
          ? semi_pos
          : bracket_pos;
#else
  constexpr std::size_t type_end = function.rfind(suffix);
#endif

  static_assert(type_end != std::string_view::npos, "Could not find type suffix");
  static_assert(type_end > type_start, "Invalid type name bounds");

  return function.substr(type_start, type_end - type_start);
}

}  // namespace detail

// ============================================================================
// Public API
// ============================================================================

/**
 * Get the name of a type as a compile-time string_view.
 *
 * This uses compiler intrinsics to extract human-readable type names
 * without requiring RTTI.
 *
 * @tparam T The type to get the name of
 * @return A string_view containing the type name
 *
 * Example:
 *   constexpr auto name = type_name<int>();  // "int"
 *   constexpr auto name2 = type_name<std::vector<int>>();  // "std::vector<int, ...>"
 */
template <typename T>
[[nodiscard]] consteval std::string_view type_name() noexcept {
  return detail::type_name_impl<T>();
}

/**
 * Get the type name as a fixed-size array for use as NTTP.
 *
 * Since string_view can't always be used as NTTP (depends on storage),
 * this returns the type name as a std::array that can be used anywhere.
 *
 * @tparam T The type to get the name of
 * @return A std::array containing the type name characters
 */
template <typename T>
[[nodiscard]] consteval auto type_name_array() noexcept {
  constexpr auto name = type_name<T>();
  std::array<char, name.size()> result{};
  for (std::size_t i = 0; i < name.size(); ++i) {
    result[i] = name[i];
  }
  return result;
}

/**
 * Compile-time type ID based on hash of type name.
 *
 * Provides a unique (within hash collision probability) identifier
 * for any type, usable at compile-time.
 *
 * @tparam T The type to get an ID for
 *
 * Example:
 *   static_assert(type_id<int> != type_id<float>);
 *   static_assert(type_id<int> == type_id<int>);
 */
template <typename T>
inline constexpr std::size_t type_id = fnv1a(type_name<T>());

/**
 * Check if two types have the same type_id.
 *
 * This is essentially a constexpr version of checking typeid equality.
 */
template <typename T, typename U>
inline constexpr bool same_type_id = (type_id<T> == type_id<U>);

// ============================================================================
// Type name comparison utilities
// ============================================================================

/**
 * Compare type names at compile-time.
 */
template <typename T, typename U>
[[nodiscard]] consteval bool type_names_equal() noexcept {
  return type_name<T>() == type_name<U>();
}

/**
 * Check if type name contains a substring.
 *
 * Useful for template metaprogramming based on type characteristics.
 *
 * Example:
 *   static_assert(type_name_contains<std::vector<int>>("vector"));
 */
template <typename T>
[[nodiscard]] consteval bool type_name_contains(std::string_view substr) noexcept {
  return type_name<T>().find(substr) != std::string_view::npos;
}

/**
 * Check if type name starts with a prefix.
 */
template <typename T>
[[nodiscard]] consteval bool type_name_starts_with(std::string_view prefix) noexcept {
  return type_name<T>().starts_with(prefix);
}

/**
 * Check if type name ends with a suffix.
 */
template <typename T>
[[nodiscard]] consteval bool type_name_ends_with(std::string_view suffix) noexcept {
  return type_name<T>().ends_with(suffix);
}

// ============================================================================
// Type registration helper
// ============================================================================

/**
 * A type wrapper that carries its name as a compile-time constant.
 *
 * Useful for type registration patterns.
 *
 * Example:
 *   using IntType = named_type<int>;
 *   constexpr auto name = IntType::name;  // "int"
 */
template <typename T>
struct named_type {
  using type = T;
  static constexpr std::string_view name = type_name<T>();
  static constexpr std::size_t id = type_id<T>;
};

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_TYPE_NAME_H
/* end file ConstexprCore/type_name.h */
/* begin file ConstexprCore/utf_convert.h */
#ifndef CONSTEXPRCORE_UTF_CONVERT_H
#define CONSTEXPRCORE_UTF_CONVERT_H

/* skipped duplicate ConstexprCore/constexpr_check.h */
/* skipped duplicate ConstexprCore/fixed_string.h */

#include <cstddef>
#include <cstdint>

namespace ConstexprCore {

// ============================================================================
// UTF-8 validation error types
// ============================================================================

/**
 * Specific UTF-8 validation error codes.
 *
 * These provide detailed information about why validation failed.
 */
enum class utf8_error {
  none = 0,                    // No error (valid UTF-8)
  truncated_sequence,          // Multi-byte sequence cut off before end
  invalid_continuation_byte,   // Expected continuation byte (10xxxxxx), got something else
  overlong_encoding,           // Code point encoded with more bytes than necessary
  surrogate_code_point,        // UTF-16 surrogate (U+D800-U+DFFF) encoded in UTF-8
  invalid_code_point,          // Code point > U+10FFFF
  invalid_lead_byte            // Byte doesn't match any valid UTF-8 lead pattern
};

/**
 * UTF-8 validation result with error details.
 */
using utf8_validation_result = error_result<utf8_error>;

// ============================================================================
// Compile-time UTF conversion utilities (internal)
// ============================================================================

namespace detail {

/**
 * UTF-8 sequence length from lead byte.
 *
 * @note Does NOT validate. Returns 4 for any byte >= 0xF0, even invalid ones.
 *       Use validate_utf8<>() for validation.
 */
constexpr std::size_t utf8_seq_len(unsigned char lead) noexcept {
  if ((lead & 0x80) == 0) return 1;
  if ((lead & 0xE0) == 0xC0) return 2;
  if ((lead & 0xF0) == 0xE0) return 3;
  return 4;
}

/**
 * UTF-16 encoded size for a code point.
 *
 * @note Does NOT validate. Assumes cp is a valid Unicode code point.
 */
constexpr std::size_t utf16_encoded_size(char32_t cp) noexcept {
  return cp >= 0x10000 ? 2 : 1;
}

/**
 * Decode one UTF-8 code point, returns {code_point, bytes_consumed}.
 *
 * @note Does NOT validate. Assumes the input is well-formed UTF-8.
 *       For untrusted input, use validate_utf8<>() first.
 */
constexpr std::pair<char32_t, std::size_t> decode_utf8(const char* str) noexcept {
  unsigned char lead = static_cast<unsigned char>(*str);

  if ((lead & 0x80) == 0) {
    return {lead, 1};
  }
  if ((lead & 0xE0) == 0xC0) {
    char32_t cp = (lead & 0x1F) << 6;
    cp |= (static_cast<unsigned char>(str[1]) & 0x3F);
    return {cp, 2};
  }
  if ((lead & 0xF0) == 0xE0) {
    char32_t cp = (lead & 0x0F) << 12;
    cp |= (static_cast<unsigned char>(str[1]) & 0x3F) << 6;
    cp |= (static_cast<unsigned char>(str[2]) & 0x3F);
    return {cp, 3};
  }
  char32_t cp = (lead & 0x07) << 18;
  cp |= (static_cast<unsigned char>(str[1]) & 0x3F) << 12;
  cp |= (static_cast<unsigned char>(str[2]) & 0x3F) << 6;
  cp |= (static_cast<unsigned char>(str[3]) & 0x3F);
  return {cp, 4};
}

// Size calculation for fixed_string (assumes valid UTF-8)
template <fixed_string Str>
consteval std::size_t utf8_to_utf16_size() noexcept {
  std::size_t result = 0;
  std::size_t i = 0;
  while (i < Str.size()) {
    auto [cp, consumed] = decode_utf8(&Str.data[i]);
    result += utf16_encoded_size(cp);
    i += consumed;
  }
  return result;
}

template <fixed_string Str>
consteval std::size_t utf8_to_utf32_size() noexcept {
  std::size_t result = 0;
  std::size_t i = 0;
  while (i < Str.size()) {
    i += utf8_seq_len(static_cast<unsigned char>(Str.data[i]));
    ++result;
  }
  return result;
}

/**
 * Encode a single code point to UTF-16, returns number of code units written.
 *
 * @note Does NOT validate. Assumes cp is a valid Unicode code point (not a surrogate).
 */
constexpr std::size_t encode_utf16(char32_t cp, char16_t* out) noexcept {
  if (cp < 0x10000) {
    out[0] = static_cast<char16_t>(cp);
    return 1;
  }
  char32_t adjusted = cp - 0x10000;
  out[0] = static_cast<char16_t>(0xD800 | (adjusted >> 10));
  out[1] = static_cast<char16_t>(0xDC00 | (adjusted & 0x3FF));
  return 2;
}

constexpr bool is_valid_utf8_continuation(unsigned char c) noexcept {
  return (c & 0xC0) == 0x80;
}

}  // namespace detail

// ============================================================================
// UTF-8 validation
// ============================================================================

/**
 * Validate UTF-8 string and return detailed error information.
 *
 * Returns a utf8_validation_result containing:
 * - error: The specific error code (utf8_error::none if valid)
 * - position: Byte offset where the error was detected
 *
 * Example:
 *   constexpr auto result = validate_utf8<"Hello">();
 *   static_assert(result.ok());
 *
 *   constexpr auto bad = validate_utf8<"\xFF">();
 *   static_assert(bad.error == utf8_error::invalid_lead_byte);
 *   static_assert(bad.position == 0);
 */
template <fixed_string Str>
consteval utf8_validation_result validate_utf8() noexcept {
  std::size_t i = 0;
  while (i < Str.size()) {
    unsigned char lead = static_cast<unsigned char>(Str.data[i]);

    if ((lead & 0x80) == 0) {
      // ASCII - always valid
      i += 1;
    } else if ((lead & 0xE0) == 0xC0) {
      // 2-byte sequence
      if (i + 1 >= Str.size()) {
        return {utf8_error::truncated_sequence, i};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 1]))) {
        return {utf8_error::invalid_continuation_byte, i + 1};
      }
      // Check for overlong encoding (code points < 0x80 must use 1 byte)
      if (lead < 0xC2) {
        return {utf8_error::overlong_encoding, i};
      }
      i += 2;
    } else if ((lead & 0xF0) == 0xE0) {
      // 3-byte sequence
      if (i + 2 >= Str.size()) {
        return {utf8_error::truncated_sequence, i};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 1]))) {
        return {utf8_error::invalid_continuation_byte, i + 1};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 2]))) {
        return {utf8_error::invalid_continuation_byte, i + 2};
      }
      // Decode and check for overlong encoding and surrogate range
      char32_t cp =
          ((lead & 0x0F) << 12) |
          ((static_cast<unsigned char>(Str.data[i + 1]) & 0x3F) << 6) |
          (static_cast<unsigned char>(Str.data[i + 2]) & 0x3F);
      if (cp < 0x800) {
        return {utf8_error::overlong_encoding, i};
      }
      if (cp >= 0xD800 && cp <= 0xDFFF) {
        return {utf8_error::surrogate_code_point, i};
      }
      i += 3;
    } else if ((lead & 0xF8) == 0xF0) {
      // 4-byte sequence
      if (i + 3 >= Str.size()) {
        return {utf8_error::truncated_sequence, i};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 1]))) {
        return {utf8_error::invalid_continuation_byte, i + 1};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 2]))) {
        return {utf8_error::invalid_continuation_byte, i + 2};
      }
      if (!detail::is_valid_utf8_continuation(
              static_cast<unsigned char>(Str.data[i + 3]))) {
        return {utf8_error::invalid_continuation_byte, i + 3};
      }
      // Decode and check range
      char32_t cp =
          ((lead & 0x07) << 18) |
          ((static_cast<unsigned char>(Str.data[i + 1]) & 0x3F) << 12) |
          ((static_cast<unsigned char>(Str.data[i + 2]) & 0x3F) << 6) |
          (static_cast<unsigned char>(Str.data[i + 3]) & 0x3F);
      if (cp < 0x10000) {
        return {utf8_error::overlong_encoding, i};
      }
      if (cp > 0x10FFFF) {
        return {utf8_error::invalid_code_point, i};
      }
      i += 4;
    } else {
      // Invalid lead byte (0x80-0xBF are continuation bytes, 0xF8+ invalid)
      return {utf8_error::invalid_lead_byte, i};
    }
  }
  return {utf8_error::none, 0};
}

/**
 * Check if a string is valid UTF-8 at compile time.
 *
 * Simple boolean check. For detailed error information, use validate_utf8<>().
 *
 * Example:
 *   static_assert(is_valid_utf8<"Hello">());
 *   static_assert(is_valid_utf8<"\xE2\x82\xAC">());  // Valid Euro sign
 */
template <fixed_string Str>
consteval bool is_valid_utf8() noexcept {
  return validate_utf8<Str>().ok();
}

/**
 * Require valid UTF-8, triggering a compile-time error if invalid.
 *
 * Use this when you want a clear compile-time error for invalid input.
 *
 * Example:
 *   template <fixed_string Str>
 *   consteval auto process_utf8() {
 *     require_valid_utf8<Str>();  // Compile error if invalid
 *     return utf8_to_utf32<Str>();
 *   }
 */
template <fixed_string Str>
consteval void require_valid_utf8() {
  constexpr auto result = validate_utf8<Str>();
  if constexpr (!result.ok()) {
    // Provide specific error messages based on error type
    if constexpr (result.error == utf8_error::truncated_sequence) {
      static_error("Invalid UTF-8: truncated multi-byte sequence");
    } else if constexpr (result.error == utf8_error::invalid_continuation_byte) {
      static_error("Invalid UTF-8: expected continuation byte");
    } else if constexpr (result.error == utf8_error::overlong_encoding) {
      static_error("Invalid UTF-8: overlong encoding");
    } else if constexpr (result.error == utf8_error::surrogate_code_point) {
      static_error("Invalid UTF-8: surrogate code point (U+D800-U+DFFF)");
    } else if constexpr (result.error == utf8_error::invalid_code_point) {
      static_error("Invalid UTF-8: code point exceeds U+10FFFF");
    } else if constexpr (result.error == utf8_error::invalid_lead_byte) {
      static_error("Invalid UTF-8: invalid lead byte");
    } else {
      static_error("Invalid UTF-8");
    }
  }
}

// ============================================================================
// UTF-8 to UTF-16 conversion
// ============================================================================

/**
 * Convert UTF-8 string to UTF-16 at compile time.
 *
 * @note Does NOT validate input. For untrusted input, call require_valid_utf8<Str>()
 *       first, or use is_valid_utf8<Str>() to check before conversion.
 *
 * @tparam Str The UTF-8 string literal as fixed_string
 * @return A fixed_string<char16_t, N> containing the UTF-16 result
 *
 * Example:
 *   constexpr auto utf16 = utf8_to_utf16<"Hello">();
 *   constexpr auto utf16_euro = utf8_to_utf16<"Price: \xE2\x82\xAC">();
 */
template <fixed_string Str>
consteval auto utf8_to_utf16() {
  constexpr std::size_t output_len = detail::utf8_to_utf16_size<Str>();

  fixed_string<char16_t, output_len> result{};

  std::size_t in_idx = 0;
  std::size_t out_idx = 0;

  while (in_idx < Str.size()) {
    auto [cp, consumed] = detail::decode_utf8(&Str.data[in_idx]);
    in_idx += consumed;
    out_idx += detail::encode_utf16(cp, &result.data[out_idx]);
  }

  return result;
}

/**
 * Convert UTF-8 to UTF-16 with validation.
 *
 * Triggers a compile-time error if the input is not valid UTF-8.
 *
 * Example:
 *   constexpr auto utf16 = utf8_to_utf16_checked<"Hello">();  // OK
 *   constexpr auto bad = utf8_to_utf16_checked<"\xFF">();     // Compile error!
 */
template <fixed_string Str>
consteval auto utf8_to_utf16_checked() {
  require_valid_utf8<Str>();
  return utf8_to_utf16<Str>();
}

// ============================================================================
// UTF-8 to UTF-32 conversion
// ============================================================================

/**
 * Convert UTF-8 string to UTF-32 at compile time.
 *
 * @note Does NOT validate input. For untrusted input, call require_valid_utf8<Str>()
 *       first, or use is_valid_utf8<Str>() to check before conversion.
 *
 * Example:
 *   constexpr auto utf32 = utf8_to_utf32<"Hello">();
 */
template <fixed_string Str>
consteval auto utf8_to_utf32() {
  constexpr std::size_t output_len = detail::utf8_to_utf32_size<Str>();

  fixed_string<char32_t, output_len> result{};

  std::size_t in_idx = 0;
  std::size_t out_idx = 0;

  while (in_idx < Str.size()) {
    auto [cp, consumed] = detail::decode_utf8(&Str.data[in_idx]);
    result.data[out_idx++] = cp;
    in_idx += consumed;
  }

  return result;
}

/**
 * Convert UTF-8 to UTF-32 with validation.
 *
 * Triggers a compile-time error if the input is not valid UTF-8.
 *
 * Example:
 *   constexpr auto utf32 = utf8_to_utf32_checked<"Hello">();  // OK
 *   constexpr auto bad = utf8_to_utf32_checked<"\xFF">();     // Compile error!
 */
template <fixed_string Str>
consteval auto utf8_to_utf32_checked() {
  require_valid_utf8<Str>();
  return utf8_to_utf32<Str>();
}

// ============================================================================
// Code point counting utilities
// ============================================================================

/**
 * Count the number of Unicode code points in a UTF-8 string.
 *
 * @note Does NOT validate. For invalid UTF-8, the count may be incorrect.
 *
 * Example:
 *   static_assert(utf8_code_point_count<"Hello">() == 5);
 *   static_assert(utf8_code_point_count<"\xE2\x82\xAC">() == 1);  // Euro sign
 */
template <fixed_string Str>
consteval std::size_t utf8_code_point_count() noexcept {
  return detail::utf8_to_utf32_size<Str>();
}

/**
 * Count the number of UTF-16 code units needed to encode a UTF-8 string.
 *
 * @note Does NOT validate. For invalid UTF-8, the count may be incorrect.
 */
template <fixed_string Str>
consteval std::size_t utf8_to_utf16_length() noexcept {
  return detail::utf8_to_utf16_size<Str>();
}

}  // namespace ConstexprCore

#endif  // CONSTEXPRCORE_UTF_CONVERT_H
/* end file ConstexprCore/utf_convert.h */

#endif // CONSTEXPRCORE_USEFUL_ABSTRACTIONS_H
/* end file ConstexprCore/useful_abstractions.h */
